booking_site/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('booking_system/', include('booking_system.urls'))
]

booking_system/urls.py
from django.urls import path
from . import views

app_name = 'booking_system'
urlpatterns = [
    path('',views.entrance, name='entrance'),
    path('index/', views.index, name='index'),
    path('login/', views.login, name='login'),
    path('register/', views.register, name='register'),
    path('logout/', views.logout, name='logout'),
    path('flight-query/', views.flight_query, name='flight_query'),
    path('flight-display/', views.flight_display, name='flight_display'),
]

booking_system/models.py
from django.db import models

# Create your models here.

booking_system/views.py
from django.template import loader
from django.shortcuts import render
from django.http import HttpResponse, HttpResponseRedirect
from django.urls import reverse
from django.db import connection
from collections import namedtuple

DATABASE_NAME = 'bookdb'

# Create your views here.
def entrance(request):
    return HttpResponseRedirect(reverse('booking_system:login'))


def index(request):
    if request.session.get('is_login'):
        context = {
            'session' : request.session,
        }
        return render(request, 'booking_system/index.html', context)
    else:
        return HttpResponseRedirect(reverse('booking_system:login'))


def login(request):
    if request.method == 'POST':
        username = request.POST.get('username')
        password = request.POST.get('password')
        request.session['is_login'] = True
        request.session['username'] = username
        request.session['password'] = password
        return HttpResponseRedirect(reverse('booking_system:index'))
    else:
        return render(request, 'booking_system/login.html')


def register(request):
    if request.method == 'POST':
        # username = request.POST.get('username')
        # password = request.POST.get('password')
        return render(request, 'booking_system/login.html')
    else:
        return render(request, 'booking_system/register.html')


def logout(request):
    request.session.flush()
    return HttpResponseRedirect(reverse('booking_system:login'))


def flight_query(request):
    context = {
        'session' : request.session,
    }
    return render(request, 'booking_system/flight_query.html', context)


def flight_display(request):
    context = {
        'session' : request.session,
    }
    return render(request, 'booking_system/flight_display.html', context)


def namedtuple_fetchall(cursor):
    "Return all rows from a cursor as a namedtuple"
    desc = cursor.description
    nt_result = namedtuple('Result', [col[0] for col in desc])
    return [nt_result(*row) for row in cursor.fetchall()]

templates/base.html
{% load static %}
 
<!DOCTYPE html>
<html lang="zh-CN">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!-- 上述3个meta标签*必须*放在最前面，任何其他内容都*必须*跟随其后！ -->
    <title> {% block title %} 订票系统 {% endblock %} </title>
 
    <!-- Bootstrap -->
    <link href="{% static 'bootstrap/css/bootstrap.min.css' %}" rel="stylesheet">
 
    <!-- HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
      <script src="https://cdn.bootcss.com/html5shiv/3.7.3/html5shiv.min.js"></script>
      <script src="https://cdn.bootcss.com/respond.js/1.4.2/respond.min.js"></script>
    <![endif]-->
    {% block css %} {% endblock %}
  </head>
  <body>
    <nav class="navbar navbar-default navbar-fixed-top">
      <div class="container-fluid">
        <!-- Brand and toggle get grouped for better mobile display -->
        <div class="navbar-header">
          <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-nav" aria-expanded="false">
            <span class="sr-only">切换导航条</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <a class="navbar-brand" href="#">Booking System</a>
        </div>
 
        <!-- Collect the nav links, forms, and other content for toggling -->
        <div class="collapse navbar-collapse" id="bs-nav">
          <ul class="nav navbar-nav">
            <li class="active"><a href="/booking_system/index/">主页</a></li>
          </ul>
          <ul class="nav navbar-nav navbar-right">
            {% block navbar_right %} {% endblock %}
          </ul>
        </div><!-- /.navbar-collapse -->
      </div><!-- /.container-fluid -->
    </nav>
 
    {% block content %}{% endblock %}
 
 
    <!-- jQuery (necessary for Bootstrap's JavaScript plugins) -->
    <script src="{% static 'js/jquery.js' %}"></script>
    <!-- Include all compiled plugins (below), or include individual files as needed -->
    <script src="{% static 'bootstrap/js/bootstrap.min.js' %}"></script>
  </body>
</html>

templates/booking_system/flight_display.html
{% extends "base.html" %}
{% load static %}

{% block title %}
  订票系统：航班列表
{% endblock %}

{% block css %}
  <link href="{% static 'css/flight_display.css' %}" rel="stylesheet">
{% endblock %}

{% block navbar_right %}
  {% if session.is_login %}
    <li><a> {{ session.username }} </a></li>
    <li> <a href="/booking_system/logout/"> 注销 </a></li>
  {% else %}
    <li><a href="/booking_system/login/">登录</a></li>
    <li><a href="/booking_system/register/">注册</a></li>
  {% endif %}
{% endblock %}

templates/booking_system/flight_query.html
{% extends "base.html" %}
{% load static %}

{% block title %}
  订票系统：查询航班
{% endblock %}

{% block css %}
  <link href="{% static 'css/flight_query.css' %}" rel="stylesheet">
{% endblock %}

{% block navbar_right %}
  {% if session.is_login %}
    <li><a> {{ session.username }} </a></li>
    <li> <a href="/booking_system/logout/"> 注销 </a></li>
  {% else %}
    <li><a href="/booking_system/login/">登录</a></li>
    <li><a href="/booking_system/register/">注册</a></li>
  {% endif %}
{% endblock %}

templates/booking_system/index.html
{% extends "base.html" %}
{% load static %}

{% block title %}
  订票系统：主页
{% endblock %}

{% block css %}
  <link href="{% static 'css/index.css' %}" rel="stylesheet">
{% endblock %}

{% block navbar_right %}
  {% if session.is_login %}
    <li><a> {{ session.username }} </a></li>
    <li> <a href="/booking_system/logout/"> 注销 </a></li>
  {% else %}
    <li><a href="/booking_system/login/">登录</a></li>
    <li><a href="/booking_system/register/">注册</a></li>
  {% endif %}
{% endblock %}

{% block content %}

    <!-- Main jumbotron for a primary marketing message or call to action -->
    <div class="jumbotron">
      <div class="container">
        <h1> 欢迎登录 <br/> 机票订购系统 </h1>
      </div>
    </div>

    <div class="container">
      <!-- Example row of columns -->
      <div class="row">
        <div class="col-md-6">
          <div class="nav-prompt">
            <h2> 查询航班 </h2>
            <p> 您可以根据出发地、目的地和日期查询航班。 </p>
            <p> 选择适合您的航班，购买机票。 </p>
          </div>
          <p><a class="btn btn-default" href="/booking_system/flight-query/" role="button">View details &raquo;</a></p>
        </div>
        <div class="col-md-6">
          <div class="nav-prompt">
            <h2> 查询订单 </h2>
            <p> 在这里查询您的交易订单。 </p>
          </div>
          <p><a class="btn btn-default" href="#" role="button">View details &raquo;</a></p>
        </div>
      </div>

      <hr>

      <footer>
        <p>  </p>
      </footer>
    </div> <!-- /container -->

{% endblock %}

templates/booking_system/login.html
{% extends "base.html" %}
{% load static %}

{% block title %}
  订票系统：登录
{% endblock %}

{% block css %}
  <link href="{% static 'css/login.css' %}" rel="stylesheet">
{% endblock %}

{% block navbar_right %}
    <li><a href="/booking_system/register/">注册</a></li>
{% endblock %}

{% block content %}

<div class="container">

  <form class="form-login" action={% url 'booking_system:login' %} method="POST">
    {% csrf_token %}
    <h2 class="form-login-heading"> 用户登录 </h2>

    <div class="form-group">
      <label for="inputUsername"> 用户名 </label>
      <input type="text" id="inputUsername" name="username" class="form-control" placeholder="Username" required autofocus>
    </div>

    <div class="form-group">
      <label for="inputPassword"> 密码 </label>
      <input type="password" id="inputPassword" name="password" class="form-control" placeholder="Password" required>
    </div>

    <div class="form-group">
      <button class="btn btn-lg btn-primary btn-block" type="submit">Login</button>
    </div>
  </form>

</div> <!-- /container -->

{% endblock %}

templates/booking_system/register.html
{% extends "base.html" %}
{% load static %}

{% block title %}
  订票系统：注册
{% endblock %}

{% block css %}
  <link href="{% static 'css/register.css' %}" rel="stylesheet">
{% endblock %}

{% block navbar_right %}
    <li><a href="/booking_system/login/">已有账号？点此登录</a></li>
{% endblock %}

{% block content %}

<div class="container">

  <form class="form-login" action={% url 'booking_system:register' %} method="POST">
    {% csrf_token %}
    <h2 class="form-login-heading"> 用户注册 </h2>

    <div class="form-group">
      <label for="inputUsername"> 用户名 </label>
      <input type="text" id="inputUsername" name="username" class="form-control" placeholder="Username" required autofocus>
    </div>

    <div class="form-group">
      <label for="inputPassword"> 密码 </label>
      <input type="password" id="inputPassword" name="password" class="form-control" placeholder="Password" required>
    </div>

    <div class="form-group">
      <label for="inputComfirmation"> 确认密码 </label>
      <input type="password" id="inputConfirmation" name="comfirmation" class="form-control" placeholder="Comfirm password" required>
    </div>

    <div class="form-group">
      <button class="btn btn-lg btn-primary btn-block" type="submit">Register</button>
    </div>
  </form>

</div> <!-- /container -->

{% endblock %}